### ISSUE TITLE
使用toy datasets代码无法成功运行

### ISSUE THREAD

**Issue by Daiqh1** [weiyinwei/MMGCN#32]

**Comment by weiyinwei** [comment]
Could you provide some details about your issue?

**Comment by Daiqh1** [comment]
我无法使用README.md中的环境所以我使用如下
```
python 3.6
torch==1.4.0
torch-cluster==1.5.2   
torch-geometric==1.4.1   
torch-scatter==2.0.3
torch-sparse==0.5.1 
tb-nightly
```
### 1
使用命令`python main.py --model_name='MMGCN' --l_r=0.0001 --weight_decay=0.0001 --batch_size=1024 --dim_latent=64 --num_workers=30 --aggr_mode='mean' --num_layer=2 --concat=False`
有如下报错
`main.py: error: unrecognized arguments: --model_name=MMGCN --dim_latent=64 --num_layer=2 --concat=False`
我删去了`--model_name=MMGCN --dim_latent=64 --num_layer=2 --concat=False`
### 2
```
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    num_routing = args.num_routing
AttributeError: 'Namespace' object has no attribute 'num_routing'
```
我在main.py中添加`parser.add_argument('--num_routing', type=int, default=1, help='.')`

### 3
接下来我将文件重命名使代码运行
```
train_sample.npy->train.npy
user_item_dict_sample.npy->user_item_dict.npy
v_feat_sample.npy->FeatureVideo_normal.npy
a_feat_sample.npy->FeatureAudio_avg_normal.npy
t_feat_sample.npy->FeatureText_stl_normal.npy
val_sample.npy->val_full.npy
test_sample.npy->test_full.npy
```
### 4
将Dataset.py 中 
```
num_user = 55485
num_item = 5986
```
修改为
```
 num_user = 100
 num_item = 1141
```
### 5 目前无法解决
```
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    val_precision, val_recall, val_ndcg = full_vt(epoch, model, val_data, 'Val', writer)
  File "/home/user/zz_D/MMGCN-master/Full_vt.py", line 12, in full_vt
    precision, recall, ndcg_score = model.full_accuracy(data)
  File "/home/user/zz_D/MMGCN-master/Model_MMGCN.py", line 227, in full_accuracy
    items_list = all_index_of_rank_list[user].tolist()
IndexError: index 0 is out of bounds for dimension 0 with size 0
```

**Comment by Daiqh1** [comment]
> 
> 
> Could you provide some details about your issue?

```
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    val_precision, val_recall, val_ndcg = full_vt(epoch, model, val_data, 'Val', writer)
  File "/home/user/zz_D/MMGCN-master/Full_vt.py", line 12, in full_vt
    precision, recall, ndcg_score = model.full_accuracy(data)
  File "/home/user/zz_D/MMGCN-master/Model_MMGCN.py", line 227, in full_accuracy
    items_list = all_index_of_rank_list[user].tolist()
IndexError: index 0 is out of bounds for dimension 0 with size 0
```

**Comment by weiyinwei** [comment]
这个我建议您输出一下all_index_of_list，可能为空。具体造成这个问题的原因，这样我看不出来，您可以继续跟踪一下这个错误，咱们再来讨论。

**Comment by Daiqh1** [comment]
> 
> 
> 这个我建议您输出一下all_index_of_list，可能为空。具体造成这个问题的原因，这样我看不出来，您可以继续跟踪一下这个错误，咱们再来讨论。

我无法使用README.md中的环境所以我使用如下
```
python 3.6
torch==1.4.0
torch-cluster==1.5.2   
torch-geometric==1.4.1   
torch-scatter==2.0.3
torch-sparse==0.5.1 
tb-nightly
```
### 1
使用命令`python main.py --model_name='MMGCN' --l_r=0.0001 --weight_decay=0.0001 --batch_size=1024 --dim_latent=64 --num_workers=30 --aggr_mode='mean' --num_layer=2 --concat=False`
有如下报错
`main.py: error: unrecognized arguments: --model_name=MMGCN --dim_latent=64 --num_layer=2 --concat=False`
我删去了`--model_name=MMGCN --dim_latent=64 --num_layer=2 --concat=False`
### 2
```
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    num_routing = args.num_routing
AttributeError: 'Namespace' object has no attribute 'num_routing'
```
我在main.py中添加`parser.add_argument('--num_routing', type=int, default=1, help='.')`

### 3
接下来我将文件重命名使代码运行
```
train_sample.npy->train.npy
user_item_dict_sample.npy->user_item_dict.npy
v_feat_sample.npy->FeatureVideo_normal.npy
a_feat_sample.npy->FeatureAudio_avg_normal.npy
t_feat_sample.npy->FeatureText_stl_normal.npy
val_sample.npy->val_full.npy
test_sample.npy->test_full.npy
```
### 4
将Dataset.py 中 
```
num_user = 55485
num_item = 5986
```
修改为
```
 num_user = 100
 num_item = 1141
```
### 5 目前无法解决
```
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    val_precision, val_recall, val_ndcg = full_vt(epoch, model, val_data, 'Val', writer)
  File "/home/user/zz_D/MMGCN-master/Full_vt.py", line 12, in full_vt
    precision, recall, ndcg_score = model.full_accuracy(data)
  File "/home/user/zz_D/MMGCN-master/Model_MMGCN.py", line 227, in full_accuracy
    items_list = all_index_of_rank_list[user].tolist()
IndexError: index 0 is out of bounds for dimension 0 with size 0
```
`print(all_index_of_rank_list)`输出`tensor([], dtype=torch.int64)`

**Comment by weiyinwei** [comment]
按照您的结果，应该是在计算全部打分时候出现了错误，导致输出为0. 不知道数据集读取是不是存在问题。

**Comment by Jiangrijin** [comment]
> > 请问您是否解决了以上问题？
> 
> 不 并没有

我也出现了这个问题，是step设置太大的原因。在model_routing.py的accuracy函数里有个while循环，用于计算所有user的topk item，由于user数很大，所以每次循环加载step个user来计算，最后拼接为all_index_of_rank_list。出现这个问题是因为，step的默认值是2000，而toy dataset中的user只有100，所以不会进入while循环，all_index_of_rank_list为空，后续访问就报错了
